#!/bin/bash
##
# Run pyro for the ROBuild system.
#
# Adds all the configuration files we need, and then runs with
# whatever arguments were supplied.
#

#set -x

here=$(cd "$(dirname "$0")" && pwd)
cd "$here"
if [[ "$*" =~ --config\ emulation.implementation=([a-z0-9]+) ]] ; then
    PYRO_ARCH=${BASH_REMATCH[1]}
fi
if [[ "$PYRO_ARCH" != 'aarch64' ]] ; then
    exec pyro --config-file "riscos.pyro" \
              --config-file "build.pyro" \
              --config-file "build-service.pyro" "$@"
else
    exec pyro --config-file "riscos-aarch64.pyro" \
              --config-file "build64.pyro" \
              --config-file "build-service-aarch64.pyro" "$@"
fi
